version: 1

on:
  pre-commit: [check]
  pre-push: [check]
  pre-receive: [check]

pipelines:
  check:
    jobs:
      just:
        just: check-just
      whitespace:
        just: check-whitespace
      shell:
        just: check-shell

  online-images:
    needs: [check]
    jobs:
      build:
        just: online::stable

  online-media:
    needs: [check]
    jobs:
      build:
        just: online::media

  online:
    needs: [online-images, online-media]

  next:
    needs: [check]
    jobs:
      build:
        just: online::next

  offline:
    needs: [check]
    jobs:
      build:
        just: offline-build

  offline-workstation:
    needs: [check]
    jobs:
      build:
        just: offline-workstation-build

  offline-nas:
    needs: [check]
    jobs:
      build:
        just: offline-nas-build

  release:
    needs: [online]
    jobs:
      publish:
        just: online::release

  stable-amd64:
    jobs:
      build:
        just: online::stable-amd64

  stable-arm64:
    jobs:
      build:
        just: online::stable-arm64

  stable-manifests:
    jobs:
      publish:
        just: online::stable-manifests

  media-amd64:
    jobs:
      build:
        just: online::media-amd64

  media-arm64:
    jobs:
      build:
        just: online::media-arm64

  release-assets:
    jobs:
      publish:
        just: online::release-assets

  next-amd64:
    jobs:
      build:
        just: online::next-amd64

  next-arm64:
    jobs:
      build:
        just: online::next-arm64

  next-manifests:
    jobs:
      publish:
        just: online::next-manifests

  offline-amd64:
    jobs:
      build:
        just: offline-amd64-build

  offline-arm64:
    jobs:
      build:
        just: offline-arm64-build
