FROM quay.io/fedora/fedora-coreos:stable
LABEL org.opencontainers.image.title="Workstation" \
  org.opencontainers.image.description="Nick's bootable container"
RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc && \
    curl -L -o /etc/yum.repos.d/ms-edge.repo \
      https://packages.microsoft.com/yumrepos/edge/config.repo && \
    curl -L -o /etc/yum.repos.d/ms-rhel10-prod.repo \
      https://packages.microsoft.com/yumrepos/microsoft-rhel10.0-prod/config.repo && \
    printf '\n[includepkgs]\n' && true && \
    sed -i '/^\[microsoft-rhel10.0-prod-yum\]/a includepkgs=intune-portal microsoft-identity-broker' \
      /etc/yum.repos.d/ms-rhel10-prod.repo && \
    ostree container commit
RUN rpm-ostree install -y cachefilesd \
    NetworkManager-wifi \
    aemu libvirt qemu-kvm \
    android-tools \
    cups bluez dconf-editor \
    dbus-daemon \
    flatpak \
    flatpak-spawn \
    fuse fuse-libs gvfs-fuse \
    gdm \
    gnome-control-center \
    gnome-disk-utility \
    gnome-keyring \
    gnome-session \
    gnome-shell \
    libhid hidapi \
    mesa-dri-drivers \
    microsoft-edge-stable intune-portal \
    nautilus nautilus-python python3-pygit2 \
    openrgb-udev-rules \
    pipewire \
    steam-devices \
    toolbox git \
    wireplumber \
    xdg-desktop-portal \
    xdg-desktop-portal-gtk && \
  rm -rf /var/cache/* && \
  ostree container commit
COPY cachefilesd.conf /etc/cachefilesd.conf
RUN ln -sf /usr/lib/systemd/system/graphical.target /etc/systemd/system/default.target && \
  mkdir -p /etc/systemd/system/graphical.target.wants && \
  ln -sf /usr/lib/systemd/system/gdm.service /etc/systemd/system/graphical.target.wants/gdm.service && \
  ostree container commit
RUN rm -f /etc/resolv.conf && \
  ln -s /run/NetworkManager/resolv.conf /etc/resolv.conf && \
  ostree container commit