FROM quay.io/fedora/fedora-coreos:stable
LABEL org.opencontainers.image.title="Workstation" \
  org.opencontainers.image.description="Nick's bootable container"
RUN rpm-ostree install -y cachefilesd \
    gnome-shell \
    gdm \
    gnome-session \
    gnome-control-center \
    gnome-keyring \
    gnome-disk-utility \
    xdg-desktop-portal \
    xdg-desktop-portal-gtk \
    flatpak \
    flatpak-spawn \
    dbus-daemon \
    NetworkManager-wifi \
    mesa-dri-drivers \
    pipewire \
    wireplumber \
    fuse fuse-libs gvfs-fuse \
    toolbox git podman openssh-clients \
    android-tools \
    aemu libvirt qemu-kvm \
    openrgb-udev-rules \
    libhid hidapi \
    cups bluez dconf-editor \
    nautilus nautilus-python python3-pygit2 \
    steam-devices && \
  rm -rf /var/cache/* && \
  ostree container commit
COPY cachefilesd.conf /etc/cachefilesd.conf
RUN ln -sf /usr/lib/systemd/system/graphical.target /etc/systemd/system/default.target && \
  mkdir -p /etc/systemd/system/graphical.target.wants && \
  ln -sf /usr/lib/systemd/system/gdm.service /etc/systemd/system/graphical.target.wants/gdm.service && \
  ostree container commit
RUN rm -f /etc/resolv.conf && \
  ln -s /run/NetworkManager/resolv.conf /etc/resolv.conf && \
  ostree container commit