name: Offline

on:
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: pipeline-offline
  cancel-in-progress: false

env:
  BUILDAH_ISOLATION: chroot
  IMAGE_NAMESPACE: localhost:5000/noobping

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: noobping/pipeline@continuous
        with:
          arguments: |
            --cap-jobs
            3
            check

  build:
    name: Offline ${{ matrix.profile }} (${{ matrix.platform.architecture }})
    needs: check
    runs-on: ${{ matrix.platform.runner }}
    timeout-minutes: 360
    strategy:
      fail-fast: false
      matrix:
        profile: [nas, workstation, sway]
        platform:
          - architecture: amd64
            coreos: x86_64
            runner: ubuntu-latest
          - architecture: arm64
            coreos: aarch64
            runner: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/offline-task
        with:
          profile: ${{ matrix.profile }}
          architecture: ${{ matrix.platform.architecture }}
          coreos-architecture: ${{ matrix.platform.coreos }}
          upload-ignition: >-
            ${{ matrix.profile == 'nas' &&
                matrix.platform.architecture == 'amd64' }}
